// ============================================================
// MOCK DATA - Données statiques pour démonstration
// ============================================================

export const MOCK_USERS = [
  {
    cin: '123456',
    password: 'password123',
    role: 'STUDENT',
    nom: 'HEDHILI AYA',
    email: 'aya.hedhili@issatso.rnu.tn',
    groupe: 'ING-A2-GL-03',
    filiere: 'Génie Logiciel',
  },
  {
    cin: '222222',
    password: 'password123',
    role: 'TEACHER',
    nom: 'Dr. BEN SALEM OMAR',
    email: 'o.bensalem@issatso.rnu.tn',
    grade: 'Maître de conférences',
    departement: 'Informatique',
    specialite: 'Génie Logiciel & IA',
    bureau: 'B204',
    telephone: '73 369 800',
  },
  {
    cin: '333333',
    password: 'password123',
    role: 'ADMIN',
    nom: 'ADMINISTRATION ISSATSo',
    email: 'admin@issatso.rnu.tn',
    groupe: null,
    filiere: null,
  },
]

export const MOCK_REQUESTS = [
  {
    id: 'REQ-001',
    reference: 'STG-2025-0001',
    type: 'STAGE_ETE',
    status: 'EN_ATTENTE',
    studentCin: '123456',
    studentNom: 'HEDHILI AYA',
    groupe: 'ING-A2-GL-03',
    filiere: 'Génie Logiciel',
    telephone: '22334455',
    nomEntreprise: 'TELNET Consulting',
    domaineActivite: 'Informatique / IT',
    adresseEntreprise: '12 Rue de la Liberté, Tunis',
    telEntreprise: '71234567',
    faxEntreprise: '71234568',
    siteWeb: 'www.telnet.tn',
    encadreurNom: 'Karim Ben Ammar',
    encadreurFonction: 'Chef de Projet',
    encadreurService: 'Développement Web',
    encadreurEmail: 'k.benammar@telnet.tn',
    tacheProposee: 'Développement d\'une application web de gestion des ressources humaines avec React et Spring Boot.',
    dateDebut: '2025-07-01',
    dateFin: '2025-08-31',
    studentComment: 'Je souhaite effectuer mon stage dans le domaine du développement fullstack.',
    adminComment: null,
    createdAt: '2025-03-15T10:30:00',
    updatedAt: '2025-03-15T10:30:00',
  },
  {
    id: 'REQ-002',
    reference: 'STG-2025-0002',
    type: 'STAGE_ETE',
    status: 'EN_COURS',
    studentCin: '123456',
    studentNom: 'HEDHILI AYA',
    groupe: 'ING-A2-GL-03',
    filiere: 'Génie Logiciel',
    telephone: '22334455',
    nomEntreprise: 'Vermeg',
    domaineActivite: 'Fintech / Logiciels bancaires',
    adresseEntreprise: 'Les Berges du Lac, Tunis',
    telEntreprise: '71987654',
    faxEntreprise: '',
    siteWeb: 'www.vermeg.com',
    encadreurNom: 'Sonia Mrad',
    encadreurFonction: 'Ingénieure Senior',
    encadreurService: 'R&D',
    encadreurEmail: 's.mrad@vermeg.com',
    tacheProposee: 'Intégration de microservices avec Spring Cloud et développement frontend Angular.',
    dateDebut: '2025-06-15',
    dateFin: '2025-08-15',
    studentComment: 'Stage orienté architecture microservices.',
    adminComment: 'Dossier en cours de vérification par le responsable pédagogique.',
    createdAt: '2025-02-20T14:15:00',
    updatedAt: '2025-03-01T09:00:00',
  },
  {
    id: 'REQ-003',
    reference: 'ATT-2025-0003',
    type: 'ATTESTATION',
    status: 'VALIDEE',
    studentCin: '123456',
    studentNom: 'HEDHILI AYA',
    groupe: 'ING-A2-GL-03',
    filiere: 'Génie Logiciel',
    telephone: '22334455',
    nomEntreprise: null,
    domaineActivite: null,
    adresseEntreprise: null,
    telEntreprise: null,
    faxEntreprise: null,
    siteWeb: null,
    encadreurNom: null,
    encadreurFonction: null,
    encadreurService: null,
    encadreurEmail: null,
    tacheProposee: null,
    dateDebut: null,
    dateFin: null,
    studentComment: 'Attestation de scolarité pour l\'année universitaire 2024-2025.',
    adminComment: 'Attestation générée et disponible au secrétariat.',
    createdAt: '2025-01-10T08:45:00',
    updatedAt: '2025-01-12T11:00:00',
  },
  {
    id: 'REQ-004',
    reference: 'REC-2025-0004',
    type: 'RECLAMATION',
    status: 'REFUSEE',
    studentCin: '123456',
    studentNom: 'HEDHILI AYA',
    groupe: 'ING-A2-GL-03',
    filiere: 'Génie Logiciel',
    telephone: '22334455',
    nomEntreprise: null,
    domaineActivite: null,
    adresseEntreprise: null,
    telEntreprise: null,
    faxEntreprise: null,
    siteWeb: null,
    encadreurNom: null,
    encadreurFonction: null,
    encadreurService: null,
    encadreurEmail: null,
    tacheProposee: null,
    dateDebut: null,
    dateFin: null,
    studentComment: 'Réclamation concernant la note obtenue au module Algorithmique avancée.',
    adminComment: 'Réclamation non recevable hors délai réglementaire.',
    createdAt: '2025-01-05T16:00:00',
    updatedAt: '2025-01-08T10:30:00',
  },
  {
    id: 'REQ-005',
    reference: 'STG-2025-0005',
    type: 'STAGE_ETE',
    status: 'EN_ATTENTE',
    studentCin: '444444',
    studentNom: 'TRABELSI MEHDI',
    groupe: 'ING-A2-RT-01',
    filiere: 'Réseaux et Télécommunications',
    telephone: '55667788',
    nomEntreprise: 'Tunisie Telecom',
    domaineActivite: 'Télécommunications',
    adresseEntreprise: 'Avenue Habib Bourguiba, Tunis',
    telEntreprise: '71890000',
    faxEntreprise: '71890001',
    siteWeb: 'www.tunisietelecom.tn',
    encadreurNom: 'Ahmed Karray',
    encadreurFonction: 'Ingénieur Réseau',
    encadreurService: 'Infrastructure',
    encadreurEmail: 'a.karray@tunisietelecom.tn',
    tacheProposee: 'Configuration et optimisation des équipements réseau Cisco.',
    dateDebut: '2025-07-01',
    dateFin: '2025-09-01',
    studentComment: 'Très motivé pour ce stage dans le domaine des télécommunications.',
    adminComment: null,
    createdAt: '2025-03-18T09:00:00',
    updatedAt: '2025-03-18T09:00:00',
  },
  {
    id: 'REQ-006',
    reference: 'CHG-2025-0006',
    type: 'CHANGEMENT_GROUPE',
    status: 'EN_COURS',
    studentCin: '555555',
    studentNom: 'MANSOURI SALMA',
    groupe: 'ING-A1-GE-02',
    filiere: 'Génie Electrique',
    telephone: '99112233',
    nomEntreprise: null,
    domaineActivite: null,
    adresseEntreprise: null,
    telEntreprise: null,
    faxEntreprise: null,
    siteWeb: null,
    encadreurNom: null,
    encadreurFonction: null,
    encadreurService: null,
    encadreurEmail: null,
    tacheProposee: null,
    dateDebut: null,
    dateFin: null,
    studentComment: 'Demande de changement du groupe 02 au groupe 01 pour raisons de transport.',
    adminComment: 'En attente de validation du chef de département.',
    createdAt: '2025-03-10T11:20:00',
    updatedAt: '2025-03-12T14:00:00',
  },
  {
    id: 'REQ-007',
    reference: 'ATT-2025-0007',
    type: 'ATTESTATION',
    status: 'VALIDEE',
    studentCin: '666666',
    studentNom: 'BOUAZIZI YOUSSEF',
    groupe: 'ING-A3-GM-01',
    filiere: 'Génie Mécanique',
    telephone: '77889900',
    nomEntreprise: null,
    domaineActivite: null,
    adresseEntreprise: null,
    telEntreprise: null,
    faxEntreprise: null,
    siteWeb: null,
    encadreurNom: null,
    encadreurFonction: null,
    encadreurService: null,
    encadreurEmail: null,
    tacheProposee: null,
    dateDebut: null,
    dateFin: null,
    studentComment: 'Attestation de réussite pour dossier de candidature Master.',
    adminComment: 'Document validé et signé par le directeur.',
    createdAt: '2025-02-28T13:00:00',
    updatedAt: '2025-03-01T10:00:00',
  },
  {
    id: 'REQ-008',
    reference: 'STG-2025-0008',
    type: 'STAGE_ETE',
    status: 'BROUILLON',
    studentCin: '123456',
    studentNom: 'HEDHILI AYA',
    groupe: 'ING-A2-GL-03',
    filiere: 'Génie Logiciel',
    telephone: '',
    nomEntreprise: 'Wevioo',
    domaineActivite: '',
    adresseEntreprise: '',
    telEntreprise: '',
    faxEntreprise: '',
    siteWeb: '',
    encadreurNom: '',
    encadreurFonction: '',
    encadreurService: '',
    encadreurEmail: '',
    tacheProposee: '',
    dateDebut: '',
    dateFin: '',
    studentComment: 'Brouillon en cours de rédaction.',
    adminComment: null,
    createdAt: '2025-03-20T17:30:00',
    updatedAt: '2025-03-20T17:30:00',
  },
]

// Stats pour le dashboard admin
export const MOCK_STATS = {
  total: 8,
  enAttente: 2,
  enCours: 2,
  validees: 2,
  refusees: 1,
  brouillons: 1,
  parType: [
    { type: "Stage d'été", count: 4, color: '#4479a3' },
    { type: 'Attestation', count: 2, color: '#2f7a45' },
    { type: 'Changement groupe', count: 1, color: '#b7791f' },
    { type: 'Réclamation', count: 1, color: '#b83232' },
  ],
  evolution: [
    { month: 'Oct', count: 3 },
    { month: 'Nov', count: 5 },
    { month: 'Dec', count: 2 },
    { month: 'Jan', count: 8 },
    { month: 'Fév', count: 6 },
    { month: 'Mar', count: 8 },
  ],
}

// ============================================================
// DONNÉES ENSEIGNANT
// ============================================================

export const MOCK_TEACHER_MODULES = [
  {
    id: 'MOD-001',
    code: 'GL301',
    nom: 'Génie Logiciel Avancé',
    niveau: '3ème année',
    groupes: ['ING-A3-GL-01', 'ING-A3-GL-02'],
    heuresCM: 21,
    heuresTD: 21,
    heuresTP: 0,
    semestre: 'S5',
    anneeUniv: '2024-2025',
  },
  {
    id: 'MOD-002',
    code: 'GL201',
    nom: 'Algorithmique Avancée',
    niveau: '2ème année',
    groupes: ['ING-A2-GL-03', 'ING-A2-GL-04'],
    heuresCM: 21,
    heuresTD: 42,
    heuresTP: 21,
    semestre: 'S3',
    anneeUniv: '2024-2025',
  },
  {
    id: 'MOD-003',
    code: 'IA401',
    nom: 'Intelligence Artificielle',
    niveau: '4ème année',
    groupes: ['ING-A4-GL-01'],
    heuresCM: 21,
    heuresTD: 21,
    heuresTP: 21,
    semestre: 'S7',
    anneeUniv: '2024-2025',
  },
  {
    id: 'MOD-004',
    code: 'GL102',
    nom: 'Programmation Orientée Objet',
    niveau: '1ère année',
    groupes: ['ING-A1-GL-01', 'ING-A1-GL-02', 'ING-A1-GL-03'],
    heuresCM: 14,
    heuresTD: 21,
    heuresTP: 21,
    semestre: 'S2',
    anneeUniv: '2024-2025',
  },
]

export const MOCK_TEACHER_STAGES = [
  {
    id: 'STG-ENC-001',
    etudiantNom: 'HEDHILI AYA',
    etudiantCin: '123456',
    groupe: 'ING-A2-GL-03',
    entreprise: 'TELNET Consulting',
    sujet: 'Développement application web RH avec React & Spring Boot',
    dateDebut: '2025-07-01',
    dateFin: '2025-08-31',
    statut: 'EN_ATTENTE_VALIDATION',
    noteFinale: null,
    rapport: false,
    soutenance: null,
  },
  {
    id: 'STG-ENC-002',
    etudiantNom: 'TRABELSI MEHDI',
    etudiantCin: '444444',
    groupe: 'ING-A3-GL-01',
    entreprise: 'Vermeg',
    sujet: 'Intégration microservices avec Spring Cloud',
    dateDebut: '2025-06-15',
    dateFin: '2025-08-15',
    statut: 'EN_COURS',
    noteFinale: null,
    rapport: true,
    soutenance: '2025-09-05',
  },
  {
    id: 'STG-ENC-003',
    etudiantNom: 'MANSOURI SALMA',
    etudiantCin: '555555',
    groupe: 'ING-A3-GL-02',
    entreprise: 'Wevioo',
    sujet: 'Développement d\'un dashboard analytique avec Angular',
    dateDebut: '2025-07-01',
    dateFin: '2025-08-31',
    statut: 'EN_COURS',
    noteFinale: null,
    rapport: false,
    soutenance: null,
  },
  {
    id: 'STG-ENC-004',
    etudiantNom: 'BOUAZIZI YOUSSEF',
    etudiantCin: '666666',
    groupe: 'ING-A3-GL-01',
    entreprise: 'Orange Tunisie',
    sujet: 'Mise en place d\'une plateforme CI/CD avec Jenkins & Docker',
    dateDebut: '2025-06-01',
    dateFin: '2025-07-31',
    statut: 'TERMINE',
    noteFinale: 16.5,
    rapport: true,
    soutenance: '2025-08-10',
  },
  {
    id: 'STG-ENC-005',
    etudiantNom: 'KARRAY NOUR',
    etudiantCin: '777777',
    groupe: 'ING-A2-GL-03',
    entreprise: 'Sofrecom',
    sujet: 'Application mobile de suivi des livraisons avec React Native',
    dateDebut: '2025-07-15',
    dateFin: '2025-09-15',
    statut: 'EN_ATTENTE_VALIDATION',
    noteFinale: null,
    rapport: false,
    soutenance: null,
  },
]

export const MOCK_TEACHER_SCHEDULE = [
  { jour: 'Lundi', heureDebut: '08:00', heureFin: '10:00', module: 'GL201 - Algorithmique Avancée', groupe: 'ING-A2-GL-03', salle: 'A101', type: 'CM' },
  { jour: 'Lundi', heureDebut: '10:00', heureFin: '12:00', module: 'GL201 - Algorithmique Avancée', groupe: 'ING-A2-GL-04', salle: 'TP02', type: 'TP' },
  { jour: 'Mardi', heureDebut: '08:00', heureFin: '10:00', module: 'GL301 - Génie Logiciel Avancé', groupe: 'ING-A3-GL-01', salle: 'B205', type: 'CM' },
  { jour: 'Mardi', heureDebut: '14:00', heureFin: '16:00', module: 'IA401 - Intelligence Artificielle', groupe: 'ING-A4-GL-01', salle: 'A203', type: 'CM' },
  { jour: 'Mercredi', heureDebut: '10:00', heureFin: '12:00', module: 'GL201 - Algorithmique Avancée', groupe: 'ING-A2-GL-03', salle: 'TD05', type: 'TD' },
  { jour: 'Jeudi', heureDebut: '08:00', heureFin: '10:00', module: 'GL301 - Génie Logiciel Avancé', groupe: 'ING-A3-GL-02', salle: 'B205', type: 'TD' },
  { jour: 'Jeudi', heureDebut: '10:00', heureFin: '12:00', module: 'IA401 - Intelligence Artificielle', groupe: 'ING-A4-GL-01', salle: 'TP01', type: 'TP' },
  { jour: 'Vendredi', heureDebut: '08:00', heureFin: '10:00', module: 'GL102 - POO', groupe: 'ING-A1-GL-01', salle: 'A101', type: 'CM' },
  { jour: 'Vendredi', heureDebut: '10:00', heureFin: '12:00', module: 'GL102 - POO', groupe: 'ING-A1-GL-02', salle: 'TP03', type: 'TP' },
]

// ============================================================
// DEMANDES ENSEIGNANT
// ============================================================
export const MOCK_TEACHER_REQUESTS = [
  {
    id: 'TREQ-001',
    reference: 'ENS-CONG-2025-001',
    type: 'CONGE_FORMATION',
    status: 'EN_ATTENTE',
    submitterRole: 'TEACHER',
    submitterCin: '222222',
    submitterNom: 'Dr. BEN SALEM OMAR',
    grade: 'Maître de conférences',
    departement: 'Informatique',
    intitule: 'Conférence internationale sur l\'IA — ICML 2025',
    lieu: 'Vienne, Autriche',
    dateDebut: '2025-07-18',
    dateFin: '2025-07-24',
    justification: 'Présentation d\'un article accepté sur les modèles de deep learning appliqués à la vision par ordinateur.',
    financementDemande: true,
    montantEstime: '1800 TND',
    documentsJoints: ['Lettre d\'acceptation ICML 2025', 'Programme de la conférence'],
    adminComment: null,
    createdAt: '2025-03-10T09:30:00',
    updatedAt: '2025-03-10T09:30:00',
  },
  {
    id: 'TREQ-002',
    reference: 'ENS-MAT-2025-002',
    type: 'DEMANDE_MATERIEL',
    status: 'EN_COURS',
    submitterRole: 'TEACHER',
    submitterCin: '222222',
    submitterNom: 'Dr. BEN SALEM OMAR',
    grade: 'Maître de conférences',
    departement: 'Informatique',
    intitule: 'Demande d\'équipement informatique — salle TP',
    lieu: null,
    dateDebut: null,
    dateFin: null,
    justification: 'Renouvellement des postes de travail de la salle TP02 pour les enseignements de programmation avancée. Les machines actuelles ne supportent plus les environnements de développement modernes.',
    financementDemande: false,
    montantEstime: null,
    documentsJoints: ['Bon de commande', 'Devis fournisseur'],
    adminComment: 'Dossier transmis au service des achats pour validation budgétaire.',
    createdAt: '2025-02-15T14:00:00',
    updatedAt: '2025-02-20T10:00:00',
  },
  {
    id: 'TREQ-003',
    reference: 'ENS-ATT-2025-003',
    type: 'ATTESTATION_SERVICE',
    status: 'VALIDEE',
    submitterRole: 'TEACHER',
    submitterCin: '222222',
    submitterNom: 'Dr. BEN SALEM OMAR',
    grade: 'Maître de conférences',
    departement: 'Informatique',
    intitule: 'Attestation de service pour dossier bancaire',
    lieu: null,
    dateDebut: null,
    dateFin: null,
    justification: 'Attestation requise pour constitution d\'un dossier de prêt immobilier.',
    financementDemande: false,
    montantEstime: null,
    documentsJoints: [],
    adminComment: 'Attestation signée et disponible au secrétariat du département.',
    createdAt: '2025-01-20T11:00:00',
    updatedAt: '2025-01-22T09:00:00',
  },
  {
    id: 'TREQ-004',
    reference: 'ENS-RECL-2025-004',
    type: 'RECLAMATION_ADMIN',
    status: 'EN_ATTENTE',
    submitterRole: 'TEACHER',
    submitterCin: '222222',
    submitterNom: 'Dr. BEN SALEM OMAR',
    grade: 'Maître de conférences',
    departement: 'Informatique',
    intitule: 'Réclamation concernant le calcul des heures supplémentaires — S1 2024/2025',
    lieu: null,
    dateDebut: null,
    dateFin: null,
    justification: 'Erreur constatée dans le décompte des heures supplémentaires effectuées au cours du premier semestre. 12 heures de TD non comptabilisées.',
    financementDemande: false,
    montantEstime: null,
    documentsJoints: ['Relevé des séances effectuées', 'Fiche d\'émargement'],
    adminComment: null,
    createdAt: '2025-03-18T16:00:00',
    updatedAt: '2025-03-18T16:00:00',
  },
]

export const MOCK_TEACHER_ACTUALITES = [
  { date: '27 Mar', titre: 'Réunion pédagogique département Informatique — 10h Salle des conférences', type: 'reunion' },
  { date: '20 Mar', titre: 'Date limite dépôt sujets PFE 2024-2025 : 15 Avril 2025', type: 'deadline' },
  { date: '15 Mar', titre: 'Calendrier des soutenances de stage d\'été publié', type: 'info' },
  { date: '10 Mar', titre: 'Formation : Outils pédagogiques numériques — inscription ouverte', type: 'formation' },
]
